### ISSUE TITLE
word timestamps crashes

### ISSUE THREAD

**Issue by eschmidbauer** [Vaibhavs10/insanely-fast-whisper#40]
when specifying word timestamps on a `3m 45s` file, I am seeing a crash
```sh
insanely-fast-whisper --file-name test.wav --timestamp word
```
```python
You are attempting to use Flash Attention 2.0 with a model initialized on CPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "insanely_fast_whisper/cli.py", line 101, in main
    outputs = pipe(
              ^^^^^
  File "transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformers/pipelines/base.py", line 1132, in __call__
    return next(
           ^^^^^
  File "transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "transformers/pipelines/pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformers/pipelines/automatic_speech_recognition.py", line 552, in _forward
    generate_kwargs["num_frames"] = stride[0] // self.feature_extractor.hop_length
                                    ~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for //: 'tuple' and 'int'
```

**Comment by eschmidbauer** [comment]
this could be related to https://github.com/huggingface/transformers/issues/27446

**Comment by sanchit-gandhi** [comment]
It is indeed related - will be fixed by https://github.com/huggingface/transformers/pull/26699.

**Comment by Vaibhavs10** [comment]
In the meantime @eschmidbauer you should be able to do the following:

```
insanely-fast-whisper --file-name test.wav --timestamp word --batch-size 1
```

It'll be slower but would do the job!

**Comment by Vaibhavs10** [comment]
(leaving this open till we patch this in transformers)

**Comment by bluusun** [comment]
Is batch-size 1 24x slower than running the default prompt?

**Comment by msj121** [comment]
@Vaibhavs10 were you able to use word level timestamp, what are your speeds? @Pranjalya seems to show not much speed improvement with word level timestamps?

**Comment by filip-alexandrov** [comment]
Just fixed by https://github.com/huggingface/transformers/pull/28114.

**Comment by gnm3000** [comment]
I didnt find a good solution for this. I need timestamp every word

> Just fixed by [huggingface/transformers#28114](https://github.com/huggingface/transformers/pull/28114).

I installed the latest transformers version, but I still getting the same error

**Comment by ArmykOliva** [comment]
This is still not fixed. It returns an error:
ValueError: WhisperFlashAttention2 attention does not support output_attentions

**Comment by Galileon** [comment]
hello
Meybe it wil help U - i am not py developer so code looks little funny but it works:
```

from nltk.tokenize import RegexpTokenizer
 tokenizer = RegexpTokenizer(r'\w+')    
            results = []

            for item in segments['chunks']:
                t1,t2 = item['timestamp'][0],item['timestamp'][1]
                oriLen = len(item['text'])
                oritext = item['text']
                timelen = t2 - t1
        
                parts = tokenizer.tokenize (item['text'])
                for part in parts:
                    partLen ,partindex = len(part) ,oritext.index(part)
                    perttime = t1 + partindex * (timelen / oriLen)
                    results.append(json.loads('{"Text":"%s","Time":"%f"}' % (part, perttime)))
        
            return results,end - start, segments['text']

```

**Comment by msj121** [comment]
@Galileon An interesting approach but keep in mind you are guessing at word level timestamps - a simple solution, but not necessarily good if you want the actual timestamp of the word. You could imagine a dynamic speaker emphasizing different words for example. But I and others appreciate the contribution.

**Comment by Galileon** [comment]
> @Galileon An interesting approach but keep in mind you are guessing at word level timestamps - a simple solution, but not necessarily good if you want the actual timestamp of the word. You could imagine a dynamic speaker emphasizing different words for example. But I and others appreciate the contribution.

hi sure i know but if someone not need ultra accouracy it will be fin le as the blovks of text are not crazy long. I will look deeper meybe into transformers code.

**Comment by PS-AI** [comment]
Timestamp=word crashes even on transformers 4.47.0. Is there any plan to fix this soon?
